version: "3"

services:
    web:
        image: node:16
        ports:
            - "3000:3000"
        volumes:
            - ./:/app
        command: bash -c "cd /app && yarn build && yarn start"
    nginx:
        image: nginx
        ports:
            - 80:80
        volumes:
            - ./dist/:/usr/share/nginx/html
